### ISSUE TITLE
ImportError: cannot import name 'ensure_dir_exists'

### ISSUE THREAD

**Issue by stenpiren** [jupyter/kernel_gateway_demos#61]
After cloning the entire repository and doing _docker-compose build_ and then _docker-compose up_ I get I get the following Traceback:

Starting scotch_demo_julia_api_1  ... **done**
Starting scotch_demo_python_api_1 ... **done**
Starting scotch_demo_r_api_1      ... **done**
Starting scotch_demo_notebook_1   ... **done**
Attaching to scotch_demo_julia_api_1, scotch_demo_python_api_1, scotch_demo_notebook_1, scotch_demo_r_api_1
**julia_api_1**   | Traceback (most recent call last):
**julia_api_1**   |   File "/opt/conda/bin/jupyter-kernelgateway", line 7, in <module>
**julia_api_1**   |     from kernel_gateway import launch_instance
**julia_api_1**   |   File "/opt/conda/lib/python3.5/site-packages/kernel_gateway/__init__.py", line 4, in <module>
**julia_api_1**   |     from .gatewayapp import launch_instance
**julia_api_1**   |   File "/opt/conda/lib/python3.5/site-packages/kernel_gateway/gatewayapp.py", line 13, in <module>
**julia_api_1**   |     from notebook.services.kernels.kernelmanager import MappingKernelManager
**julia_api_1**   |   File "/opt/conda/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
**julia_api_1**   |     from .nbextensions import install_nbextension
**julia_api_1**   |   File "/opt/conda/lib/python3.5/site-packages/notebook/nbextensions.py", line 27, in <module>
**julia_api_1**   |     from jupyter_core.utils import ensure_dir_exists
**julia_api_1**   | ImportError: cannot import name 'ensure_dir_exists'
**notebook_1**    | Traceback (most recent call last):
**notebook_1**    |   File "/opt/conda/bin/jupyter-notebook", line 7, in <module>
**notebook_1**    |     from notebook.notebookapp import main
**notebook_1**    |   File "/opt/conda/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
**notebook_1**    |     from .nbextensions import install_nbextension
**notebook_1**    |   File "/opt/conda/lib/python3.5/site-packages/notebook/nbextensions.py", line 27, in <module>
**notebook_1**    |     from jupyter_core.utils import ensure_dir_exists
**notebook_1**    | ImportError: cannot import name 'ensure_dir_exists'
**python_api_1**  | Traceback (most recent call last):
**python_api_1**  |   File "/opt/conda/bin/jupyter-kernelgateway", line 7, in <module>
**python_api_1**  |     from kernel_gateway import launch_instance
**python_api_1**  |   File "/opt/conda/lib/python3.5/site-packages/kernel_gateway/__init__.py", line 4, in <module>
**python_api_1**  |     from .gatewayapp import launch_instance
**python_api_1**  |   File "/opt/conda/lib/python3.5/site-packages/kernel_gateway/gatewayapp.py", line 13, in <module>
**python_api_1**  |     from notebook.services.kernels.kernelmanager import MappingKernelManager
**python_api_1**  |   File "/opt/conda/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
**python_api_1**  |     from .nbextensions import install_nbextension
**python_api_1**  |   File "/opt/conda/lib/python3.5/site-packages/notebook/nbextensions.py", line 27, in <module>
**python_api_1**  |     from jupyter_core.utils import ensure_dir_exists
**python_api_1**  | ImportError: cannot import name 'ensure_dir_exists'
**r_api_1**       | Traceback (most recent call last):
**r_api_1**       |   File "/opt/conda/bin/jupyter-kernelgateway", line 7, in <module>
**r_api_1**       |     from kernel_gateway import launch_instance
**r_api_1**       |   File "/opt/conda/lib/python3.5/site-packages/kernel_gateway/__init__.py", line 4, in <module>
**r_api_1**       |     from .gatewayapp import launch_instance
**r_api_1**       |   File "/opt/conda/lib/python3.5/site-packages/kernel_gateway/gatewayapp.py", line 13, in <module>
**r_api_1**       |     from notebook.services.kernels.kernelmanager import MappingKernelManager
r_api_1       |   File "/opt/conda/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
**r_api_1**       |     from .nbextensions import install_nbextension
**r_api_1**       |   File "/opt/conda/lib/python3.5/site-packages/notebook/nbextensions.py", line 27, in <module>
**r_api_1**       |     from jupyter_core.utils import ensure_dir_exists
**r_api_1**       | ImportError: cannot import name 'ensure_dir_exists'
scotch_demo_julia_api_1 exited with code 1
scotch_demo_notebook_1 exited with code 1
scotch_demo_r_api_1 exited with code 1
scotch_demo_python_api_1 exited with code 1

Thus I am unable to start any of the APIs. Any clue how to solve this?

**Comment by kevin-bates** [comment]
This implies an [update of `jupyter_core`](https://www.google.com/search?q=ensure_dir_exists&rlz=1C5CHFA_enUS739US748&oq=ensure_dir_exists&aqs=chrome..69i57j69i61j0j69i61l2.4435j0j7&sourceid=chrome&ie=UTF-8) is necessary.

Looks like Kernel Gateway's dependency on is `jupyter_core>=4.0.0`, when it should probably get updated to `jupyter_core>=4.4.0`

**Comment by stenpiren** [comment]
Hi @kevin-bates  is the update to be done inside the docker image? I googled before opening the issue as "conda update jupyter_core jupyter_client" did not help solve the issue. Any other clues?

**Comment by stenpiren** [comment]
This is my updated jupyter and dependencies. Still it outputs same error.
<img width="406" alt="screen shot 2018-07-06 at 08 36 03" src="https://user-images.githubusercontent.com/26466563/42363360-a339dacc-80f7-11e8-9709-a20c65d33223.png">

**Comment by kevin-bates** [comment]
Hi @stenpiren - thanks for the update.  I'm unfamiliar with the scotch_demo but, yes, the docker image is where the update is required.  Looking at the `Dockerfile`, I believe the issue is probably due to the demo code pinning the source docker image to a specific tag: `FROM jupyter/datascience-notebook:8015c88c4b11` which contains an older version of `jupyter_core`.

If you drop the tag portion of the `FROM` clause (e.g., `FROM jupyter/datascience-notebook`) then the latest datascience-notebook image will be used - which should have updated components.  I'm not aware of anything that would preclude JKG from working with the latest image.

Please try that next - thanks.
